Update OnePlus-SM8750-SukiSU-Ultra.yaml

diff --git a/.github/workflows/OnePlus-SM8750-SukiSU-Ultra.yaml b/.github/workflows/OnePlus-SM8750-SukiSU-Ultra.yaml
--- a/.github/workflows/OnePlus-SM8750-SukiSU-Ultra.yaml
+++ b/.github/workflows/OnePlus-SM8750-SukiSU-Ultra.yaml
@@ -125,7 +125,8 @@ jobs:
       - name: Install dependencies
         run: |
          sudo apt update && sudo apt upgrade -y
-         sudo apt install -y python3 git curl libelf-dev lld ccache
+         sudo apt install -y lld python3 p7zip-full git curl ccache libelf-dev build-essential \
+            flex bison libssl-dev libncurses-dev liblz4-tool zlib1g-dev libxml2-utils rsync unzip
 
       - name: Restore ccache
         uses: actions/cache@v4
@@ -155,11 +156,21 @@ jobs:
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" -o setup.sh && bash setup.sh susfs-main
          cd ./KernelSU
          # KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 10606)
-         KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 10700)
+         KSU_VERSION=$(expr $(git rev-list --count main 2>/dev/null || echo 13000) + 10700)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
-         export KSU_VERSION=$KSU_VERSION
-         sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
-        
+         
+         #export KSU_VERSION=$KSU_VERSION
+         #sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
+         
+         cp "${GITHUB_WORKSPACE}/.github/workflows/Bin/setup.bin" ./
+         chmod +x setup.bin
+         if [ ! -f "kernel/Makefile" ]; then
+           echo "::error ::kernel/Makefile"
+           ls -la
+           exit 1
+         fi
+         ./setup.bin
+
       - name: Set up susfs
         run: |
            cd kernel_workspace
